# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-22 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandyHelper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ManyToManyField(related_name='users_list', to='HandyHelper.User'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_category',
        ),
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.BooleanField(default=False),
        ),
    ]
