# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-22 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandyHelper', '0002_auto_20190422_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.CharField(blank=True, default=False, max_length=25),
        ),
    ]
