# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-22 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandyHelper', '0004_auto_20190422_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_owner',
            field=models.ForeignKey(on_delete='id', related_name='user_task', to='HandyHelper.User', to_field='CASCADE'),
        ),
    ]
