# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-19 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0002_auto_20190419_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_like',
            field=models.ManyToManyField(related_name='user_likes', to='quote_app.User'),
        ),
    ]
